import type { Metadata } from "next";
import { Inter } from "next/font/google";

import AppLayout from "../components/AppLayout";
import { ThemeProvider } from "../context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        {" "}
        <body className={`bg-white ${inter.className} `}>
          <AppLayout>{children}</AppLayout>
        </body>
      </html>{" "}
    </ThemeProvider>
  );
}
